FROM --platform=linux/arm/v7 python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libjpeg-dev \
    zlib1g-dev \
    libffi-dev \
    python3-dev \
    git \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY Model /app

RUN pip install --no-cache-dir --prefer-binary -r requirements.txt

RUN mkdir -p /app/temp

CMD ["python", "app-robo.py"]
