FROM arm32v7/node:23 AS builder

WORKDIR /app

COPY frontend/package*.json /app/

RUN npm install

COPY frontend/ /app/

RUN npm run build

FROM arm32v7/nginx

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]