FROM --platform=linux/arm/v7 node:23-slim AS builder

WORKDIR /app

COPY frontend/package*.json /app/

RUN npm install

COPY frontend/ /app/

RUN npm run build

FROM --platform=linux/arm/v7 nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]