FROM --platform=linux/arm/v7 python:3.9-slim

WORKDIR /app

COPY Model /app

RUN python -m venv /app/venv

RUN /app/venv/bin/pip install --no-cache-dir --prefer-binary -r requirements.txt

RUN mkdir -p /app/temp

CMD ["/app/venv/bin/python", "app-robo.py"]
