FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    python3-dev \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Model /app

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/temp

CMD ["python", "app-robo.py"]
