site_name: Cloud Computing Documentation
theme:
  name: material
nav:
  - Project Overview: 01.📘Project-Overview.md
  - Team Members: 02.👥Team-Members.md
  - Hardware & Architecture: 03.🔌Hardware-Architecture.md
  - Software Stack: 04.💻Software-Stack.md
  - System Design & Architecture: 05.🧩System-Design-&-Architecture.md
  - Sensor Node: 06.📷Sensor-Node-Setup.md
  - Object Detection & Model: 07.🧠Object-Detection-&-Model-Training.md
  - Backend: 08.🛠️Backend-Development.md
  - Frontend: 09.🌐Frontend-Development.md
  - K3s Deployment: 10.☸️Kubernetes-Cluster-Deployment-(k3s).md
  - Notification System: 11.📬Notifications-System-(Telegram-Bot).md
  - Testing & Validation: 12.✅Testing-and-Validation‐-(to-be-edited).md
  - Issues & Challenges Faced: 13.⚠️Issues-and-Challenges-Faced.md
