# ConfigMap for Beekeeper Studio connection settings (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: beekeeper-config
  namespace: default
data:
  connection.json: |
    {
      "name": "Kubernetes Postgres",
      "host": "192.168.137.178",
      "port": 30050,
      "database": "cloud-computing",
      "username": "root",
      "password": "admin",
      "type": "postgres"
    }

---

# Deployment for Beekeeper Studio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beekeeper-studio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beekeeper-studio
  template:
    metadata:
      labels:
        app: beekeeper-studio
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-5
      containers:
      - name: beekeeper-studio
        image: beekeeperstudio/beekeeper-studio:latest
        ports:
        - containerPort: 3000  # Beekeeper Studio web interface port
        resources:
          limits:
            memory: "300Mi"  # Limit to 300MB for Beekeeper
            cpu: "500m"      # Limit to 0.5 CPU cores
          requests:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: PORT
          value: "3000"
        volumeMounts:
        - name: beekeeper-config
          mountPath: "/app/config/connections.json"
          subPath: connection.json
      volumes:
      - name: beekeeper-config
        configMap:
          name: beekeeper-config
          items:
          - key: connection.json
            path: connection.json

---

apiVersion: v1
kind: Service
metadata:
  name: beekeeper-service
  namespace: default
spec:
  selector:
    app: beekeeper-studio
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30060
  type: true
  type: NodePort