apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/jenkins_home"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1  # Must be 1 due to hostPath and RWO
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        kubernetes.io/hostname: master-node
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-storage
          mountPath: "/var/jenkins_home"
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
        - name: cloud-project
          mountPath: "/home/ubuntu/cloud-computing"
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: cloud-project
        hostPath:
          path: /home/ubuntu/cloud-computing
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100
  - name: agent-port
    protocol: TCP
    port: 50000
    targetPort: 50000
    nodePort: 30101
