# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-pv
# spec:
#   volumeMode: Filesystem
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-path
#   local:
#     path: /mnt/minio-data
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - worker-node-2
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path