apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: prometheus
    component: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30030