server:
  nodeSelector:
    kubernetes.io/hostname: master-node
  service:
    type: NodePort
    nodePort: 30030

alertmanager:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: master-node

pushgateway:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: master-node
