server:
  nodeSelector:
    node-type: monitoring
  affinity: {}
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
      tolerationSeconds: null
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
      tolerationSeconds: null
  service:
    type: NodePort
    nodePort: 30030
alertmanager:
  enabled: false
pushgateway:
  enabled: false