server:
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node
  service:
    type: ClusterIP
    port: 3050
    targetPort: 3050
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
    paths:
      - /
    hosts:
      - prometheus.local
    secretName:
      - prometheus-tls

alertmanager:
  enabled: true
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node

pushgateway:
  enabled: true
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node

kubestatemetrics:
  enabled: true
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node
