server:
  nodeSelector:
    kubernetes.io/hostname: worker-node-3
  affinity: {}
  tolerations: []
  service:
    type: NodePort
    nodePort: 30030
alertmanager:
  enabled: false
pushgateway:
  enabled: false