server:
  enabled: true
  service:
    type: NodePort
    nodePort: 30030
    port: 9090
  persistentVolume:
    enabled: true
    size: 8Gi

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

pushgateway:
  enabled: false
