server:
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node
  service:
    type: NodePort
    nodePort: 30030

alertmanager:
  enabled: true
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node

pushgateway:
  enabled: true
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node

kubestatemetrics:
  enabled: true
  replicas: 2
  nodeSelector:
    kubernetes.io/hostname: master-node
