server:
  nodeSelector:
    node-type: monitoring
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - monitoring
  tolerations: []
  service:
    type: NodePort
    nodePort: 30030
alertmanager:
  enabled: false
pushgateway:
  enabled: false