name: Build and Deploy Docker Images for ARM

on:
  push:
    paths:
      - 'server/**'
      - 'frontend/**'
      - 'k3s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Detect changed directories
        id: detect_changes
        run: |
          echo "server_changed=false" >> $GITHUB_ENV
          echo "frontend_changed=false" >> $GITHUB_ENV

          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^server/'; then
            echo "server_changed=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/'; then
            echo "frontend_changed=true" >> $GITHUB_ENV
          fi

      - name: Generate image tag
        run: |
          TAG=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build & Push Server Image (ARMv7)
        if: env.server_changed == 'true'
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t kamalbhaiii/cloud-computing-server:${{ env.IMAGE_TAG }} \
            -f ./Dockerfile.server . \
            --push

      - name: Build & Push Frontend Image (ARMv7)
        if: env.frontend_changed == 'true'
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t kamalbhaiii/cloud-computing-frontend:${{ env.IMAGE_TAG }} \
            -f ./Dockerfile.frontend . \
            --push

      - name: Update image references in k3s YAML
        if: env.server_changed == 'true' || env.frontend_changed == 'true'
        run: |
          if [ "$server_changed" = "true" ]; then
            sed -i "s|kamalbhaiii/cloud-computing-server:.*|kamalbhaiii/cloud-computing-server:${IMAGE_TAG}|g" k3s/Server.yaml
          fi
          if [ "$frontend_changed" = "true" ]; then
            sed -i "s|kamalbhaiii/cloud-computing-frontend:.*|kamalbhaiii/cloud-computing-frontend:${IMAGE_TAG}|g" k3s/Frontend.yaml
          fi

      - name: Configure Git for GitHub push
        if: env.server_changed == 'true' || env.frontend_changed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit updated YAML
        if: env.server_changed == 'true' || env.frontend_changed == 'true'
        run: |
          git add k3s/*.yaml
          git commit -m "Update image tags to $IMAGE_TAG"
          git push

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://192.168.137.178:30100/job/cloud-computing/buildWithParameters" \
          --user "admin:802821b10d574a648c5dfcea971257a2" \
          --data token=cloud_computing_deploy_kamalbhaiii
