name: Build and Deploy Docker Images for ARM

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - 'frontend/**'
      - 'k3s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Detect changed directory
        id: detect_changes
        run: |
          echo "changed_dir=none" >> $GITHUB_ENV
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^server/'; then
            echo "changed_dir=server" >> $GITHUB_ENV
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/'; then
            echo "changed_dir=frontend" >> $GITHUB_ENV
          fi

      - name: Generate image tag
        run: |
          TAG=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Debug directory structure
        if: env.changed_dir == 'frontend'
        run: |
          ls -R

      - name: Build & Push Server Image
        if: env.changed_dir == 'server'
        run: |
          docker build \
            -t kamalbhaiii/cloud-computing-server:${{ env.IMAGE_TAG }} \
            -f ./Dockerfile.server . \
          && docker push kamalbhaiii/cloud-computing-server:${{ env.IMAGE_TAG }}

      - name: Build & Push Frontend Image
        if: env.changed_dir == 'frontend'
        run: |
          docker build \
            -t kamalbhaiii/cloud-computing-frontend:${{ env.IMAGE_TAG }} \
            -f ./Dockerfile.frontend . \
            --build-arg VITE_API_URL=https://api.example.com \
          && docker push kamalbhaiii/cloud-computing-frontend:${{ env.IMAGE_TAG }}

      - name: Update image reference in k3s YAML
        if: env.changed_dir != 'none'
        run: |
          if [ "${{ env.changed_dir }}" == "server" ]; then
            sed -i "s|kamalbhaiii/cloud-computing-server:.*|kamalbhaiii/cloud-computing-server:${{ env.IMAGE_TAG }}|g" k3s/Server.yaml
          elif [ "${{ env.changed_dir }}" == "frontend" ]; then
            sed -i "s|kamalbhaiii/cloud-computing-frontend:.*|kamalbhaiii/cloud-computing-frontend:${{ env.IMAGE_TAG }}|g" k3s/Frontend.yaml
          fi

      - name: Configure Git for GitHub push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit updated YAML
        if: env.changed_dir != 'none'
        run: |
          git add k3s/*.yaml
          git commit -m "Update ${{ env.changed_dir }} image tag to ${{ env.IMAGE_TAG }}"
          git push